### PR TITLE
Add ClientBuilder

### PR DESCRIPTION
**Pull request by jpochyla**
Hi! Adding a `ClientBuilder` mentioned in #9. First as a draft, missing doc comments for example, so we can agree on the approach. I understand the `::empty()` constructors on the token and credentials seem a bit weird and should be replaced by a trait impl, but that feels like stuff for another PR. So what do you think? Thanks!

### CODE REVIEW

**Comment by SabrinaJewson** [comment]
I'm not sure about exposing `debug` - that's mostly a hack I used to print out information when the tests fail. I should switch to using `#[cfg(test)]` instead actually. I think for now it would be better to not expose `access_token` since I would like to rework everything to use a trait for requesting access tokens eventually.

**Comment by jpochyla** [comment]
Sorry for the holdup, I've been busy with other work lately. I've tried to add a small async trait and move the authentication stuff there. It's not ready, missing docs and some cleaning up, but what do you think about it? Maybe the two auth flows (client credentials vs. auth code) should be separate structs?

**Comment by SabrinaJewson** [comment]
> Sorry for the holdup, I've been busy with other work lately.

That's fine! :D

> Maybe the two auth flows (client credentials vs. auth code) should be separate structs?

Yes, I think this is a very good idea.

I don't think it's a good idea to expose Reqwest in the public API (I know I already do this in the error type but I would like to change that) - in fact I think it would be nice if the fact that some authentication flows did HTTP requests to be entirely an implementation detail of that flow. Also, we can't really expect user-implementations of `Authenticator` to create an instance of this library's `Error` type, that would restrict them too much.

My suggestion for the trait is:

```rust
trait Authenticator {
    type Error;
    async fn get_token(&self) -> Result<String, Self::Error>;
}
```

Now, I'm not sure how this would affect the API functions' error types - should it be parameterized over the authenticator, parametized over the authenticator's error type, or should we erase the type entirely? The advantage of a generic parameter is that users can easily extract the underlying error using just the type system (and not downcasting tricks), but the disadvantage of a generic parameter is that it convolutes lots of the code - what do you think?

**Comment by jpochyla** [comment]
> I don't think it's a good idea to expose Reqwest in the public API (I know I already do this in the error type but I would like to change that)

It's not very pretty to have it in the trait definition, I agree. I'll remove it, the user will have to pass correct client inside. Btw, I think the error type does not really expose `reqwest::Error`, as the variant content is not public.

> Also, we can't really expect user-implementations of Authenticator to create an instance of this library's Error type, that would restrict them too much.

I think that returning `Error::Auth(AuthError { ... })` (or `Error::Io`) is for practical purposes OK. Also, adding the error to an assoc. type would make the trait object-unsafe.

**Comment by SabrinaJewson** [comment]
> Btw, I think the error type does not really expose `reqwest::Error`, as the variant content is not public.

All enum content is fully public in Rust - you can see on the docs of [`Error::Http`](https://docs.rs/aspotify/0.7/aspotify/model/enum.Error.html#variant.Http) it links to Reqwest's error type.

> I think that returning `Error::Auth(AuthError { ... })` (or `Error::Io`) is for practical purposes OK. Also, adding the error to an assoc. type would make the trait object-unsafe.

Ah, that's a good point. What about having `AuthError` be an opaque struct that internally can contain either a boxed error or `error: String` + `error_description: String`, and then `get_token` can return `Result<String, AuthError>`? This would fully decouple the authentication logic from the rest of the library logic which I think would be quite nice.

**Pull request closed without merging**
